CREATE TABLE NUMEROS_DE_SERIE(
NUMERO NVARCHAR(30),
CODIGO_INTERACAO INT
);

INSERT INTO NUMEROS_DE_SERIE(NUMERO, CODIGO_INTERACAO)
SELECT NUMERODESERIE, CODIGO_PRODUTO
FROM INTERACOES
WHERE NUMERODESERIE != '';

ALTER TABLE INTERACOES
DROP COLUMN NUMERODESERIE;